version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: blog-client
    restart: always
    links:
      - server
  
  server:
    build: ./server
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    container_name: blog-server
    restart: always
    # links:
    #   - database
